[phases.setup]
nixPkgs = ["nodejs_22", "npm-10_x"]

[phases.build]
cmds = [
  "cd client && npm install && npm run build",
  "cd server && npm install && npx prisma generate && npx prisma db push && npx tsx prisma/seed.ts"
]

[start]
cmd = "cd server && npx tsx src/index.ts"
